spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5444/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path:
  prometheus:
    metrics:
      export:
        enabled: true
