version: '3'

services:
  db:
    container_name: astra_container
    restart: always
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=astra_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5444:5432"

