server:
  port: 8080
spring:
  application:
    name: astra-service
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://postgresqldb:5432/postgres
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
  flyway:
    url: jdbc:postgresql://postgresqldb:5432/postgres
    user: postgres
    password: postgres
